<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>high</NuGetAuditLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Candoumbe.Pipelines" Version="3.1.0" />
    <PackageVersion Include="Candoumbe.Types.Strings" Version="0.4.2" />
    <PackageVersion Include="coverlet.msbuild" Version="10.0.1" />
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="FluentValidation" Version="12.1.1" />
    <PackageVersion Include="FsCheck.XUnit" Version="3.4.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.30" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="Newtonsoft.Json.Schema" Version="4.0.1" />
    <PackageVersion Include="NodaTime.Bogus" Version="3.0.2" />
    <PackageVersion Include="NodaTime.Testing" Version="3.3.3" />
    <PackageVersion Include="OneOf.Extended" Version="3.0.271" />
    <PackageVersion Include="Optional" Version="4.0.0" />
    <PackageVersion Include="Queries.Core" Version="0.4.0" />
    <PackageVersion Include="ReportGenerator" Version="5.5.11" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.15.0" />
    <PackageVersion Include="Roslynator.Formatting.Analyzers" Version="4.15.0" />
    <PackageVersion Include="Superpower" Version="3.2.1" />
    <PackageVersion Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageVersion Include="System.Linq.Queryable" Version="4.3.0" />
    <PackageVersion Include="xunit.analyzers" Version="1.27.0" />
    <PackageVersion Include="xunit.categories" Version="3.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
  <Choose>
    <When Condition="'$(TargetFramework)' == 'net10.0'">
      <ItemGroup>
        <PackageVersion Include="Ultimately" Version="4.0.0"/>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageVersion Include="Ultimately" Version="3.0.0"/>
      </ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup Condition="'$(IsTestProject)' == 'false'">
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"/>
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard1.3'">
    <PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0"/>
  </ItemGroup>
</Project>